<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="12355" started-at="2020-01-18T10:17:52Z" finished-at="2020-01-18T10:18:05Z">
    <groups>
      <group name="cucumber">
        <method signature="TestRunner$TestRunnerFile.feature(cucumber.api.testng.CucumberFeatureWrapper)[pri:0, instance:com.qa.TestRunner.TestRunner$TestRunnerFile@73ad2d6]" name="feature" class="com.qa.TestRunner.TestRunner$TestRunnerFile"/>
      </group> <!-- cucumber -->
    </groups>
    <test name="Default test" duration-ms="12355" started-at="2020-01-18T10:17:52Z" finished-at="2020-01-18T10:18:05Z">
      <class name="com.qa.TestRunner.TestRunner$TestRunnerFile">
        <test-method status="PASS" signature="setUpClass()[pri:0, instance:com.qa.TestRunner.TestRunner$TestRunnerFile@73ad2d6]" name="setUpClass" is-config="true" duration-ms="281" started-at="2020-01-18T10:17:52Z" finished-at="2020-01-18T10:17:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method status="FAIL" signature="feature(cucumber.api.testng.CucumberFeatureWrapper)[pri:0, instance:com.qa.TestRunner.TestRunner$TestRunnerFile@73ad2d6]" name="feature" duration-ms="11869" started-at="2020-01-18T10:17:53Z" description="Runs Cucumber Feature" data-provider="features" finished-at="2020-01-18T10:18:05Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Allianz Application Login Test]]>
              </value>
            </param>
          </params>
          <exception class="cucumber.runtime.CucumberException">
            <message>
              <![CDATA[java.lang.AssertionError: expected [allianz.com.au - My Portfolio] but found [Error]]]>
            </message>
            <full-stacktrace>
              <![CDATA[cucumber.runtime.CucumberException: java.lang.AssertionError: expected [allianz.com.au - My Portfolio] but found [Error]
at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
at com.qa.TestRunner.TestRunner$TestRunnerFile.feature(TestRunner.java:39)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.AssertionError: expected [allianz.com.au - My Portfolio] but found [Error]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.qa.StepDefinitions.LoginPageTest.user_is_on_the_Home_Page(LoginPageTest.java:47)
at âœ½.Then User is on the Home Page(LoginPage.feature:11)
]]>
            </full-stacktrace>
          </exception> <!-- cucumber.runtime.CucumberException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- feature -->
        <test-method status="PASS" signature="tearDownClass()[pri:0, instance:com.qa.TestRunner.TestRunner$TestRunnerFile@73ad2d6]" name="tearDownClass" is-config="true" duration-ms="73" started-at="2020-01-18T10:18:05Z" finished-at="2020-01-18T10:18:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownClass -->
      </class> <!-- com.qa.TestRunner.TestRunner$TestRunnerFile -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
